/* Generated By:JJTree: Do not edit this line. ASTAssertStatement.java */

package com.viaoa.javaparser;

public class ASTAssertStatement extends SimpleNode {
  public ASTAssertStatement(int id) {
    super(id);
  }

  public ASTAssertStatement(JavaParser p, int id) {
    super(p, id);
  }

}
