/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeBody.java */

package com.viaoa.javaparser;

public class ASTAnnotationTypeBody extends SimpleNode {
  public ASTAnnotationTypeBody(int id) {
    super(id);
  }

  public ASTAnnotationTypeBody(JavaParser p, int id) {
    super(p, id);
  }

}
