/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java */

package com.viaoa.javaparser;

public class ASTBooleanLiteral extends SimpleNode {
  public ASTBooleanLiteral(int id) {
    super(id);
  }

  public ASTBooleanLiteral(JavaParser p, int id) {
    super(p, id);
  }

}
