/* Generated By:JJTree: Do not edit this line. ASTConditionalExpression.java */

package com.viaoa.javaparser;

public class ASTConditionalExpression extends SimpleNode {
  public ASTConditionalExpression(int id) {
    super(id);
  }

  public ASTConditionalExpression(JavaParser p, int id) {
    super(p, id);
  }

}
