/* Generated By:JJTree: Do not edit this line. ASTDefaultValue.java */

package com.viaoa.javaparser;

public class ASTDefaultValue extends SimpleNode {
  public ASTDefaultValue(int id) {
    super(id);
  }

  public ASTDefaultValue(JavaParser p, int id) {
    super(p, id);
  }

}
