/* Generated By:JJTree: Do not edit this line. ASTEnumBody.java */

package com.viaoa.javaparser;

public class ASTEnumBody extends SimpleNode {
  public ASTEnumBody(int id) {
    super(id);
  }

  public ASTEnumBody(JavaParser p, int id) {
    super(p, id);
  }

}
