/* Generated By:JJTree: Do not edit this line. ASTExtendsList.java */

package com.viaoa.javaparser;

public class ASTExtendsList extends SimpleNode {
  public ASTExtendsList(int id) {
    super(id);
  }

  public ASTExtendsList(JavaParser p, int id) {
    super(p, id);
  }

}
