/* Generated By:JJTree: Do not edit this line. ASTInitializer.java */

package com.viaoa.javaparser;

public class ASTInitializer extends SimpleNode {
  public ASTInitializer(int id) {
    super(id);
  }

  public ASTInitializer(JavaParser p, int id) {
    super(p, id);
  }

}
