/* Generated By:JJTree: Do not edit this line. ASTImplementsList.java */

package com.viaoa.javaparser;

public class ASTImplementsList extends SimpleNode {
  public ASTImplementsList(int id) {
    super(id);
  }

  public ASTImplementsList(JavaParser p, int id) {
    super(p, id);
  }

}
