/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExpression.java */

package com.viaoa.javaparser;

public class ASTInstanceOfExpression extends SimpleNode {
  public ASTInstanceOfExpression(int id) {
    super(id);
  }

  public ASTInstanceOfExpression(JavaParser p, int id) {
    super(p, id);
  }

}
