/* Generated By:JJTree: Do not edit this line. ASTMarkerAnnotation.java */

package com.viaoa.javaparser;

public class ASTMarkerAnnotation extends SimpleNode {
  public ASTMarkerAnnotation(int id) {
    super(id);
  }

  public ASTMarkerAnnotation(JavaParser p, int id) {
    super(p, id);
  }

}
