/* Generated By:JJTree: Do not edit this line. ASTMemberValuePairs.java */

package com.viaoa.javaparser;

public class ASTMemberValuePairs extends SimpleNode {
  public ASTMemberValuePairs(int id) {
    super(id);
  }

  public ASTMemberValuePairs(JavaParser p, int id) {
    super(p, id);
  }

}
