/* Generated By:JJTree: Do not edit this line. ASTTypeArguments.java */

package com.viaoa.javaparser;

public class ASTTypeArguments extends SimpleNode {
  public ASTTypeArguments(int id) {
    super(id);
  }

  public ASTTypeArguments(JavaParser p, int id) {
    super(p, id);
  }

}
