/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java */

package com.viaoa.javaparser;

public class ASTUnaryExpression extends SimpleNode {
  public ASTUnaryExpression(int id) {
    super(id);
  }

  public ASTUnaryExpression(JavaParser p, int id) {
    super(p, id);
  }

}
