/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java */

package com.viaoa.javaparser;

public class ASTVariableDeclarator extends SimpleNode {
  public ASTVariableDeclarator(int id) {
    super(id);
  }

  public ASTVariableDeclarator(JavaParser p, int id) {
    super(p, id);
  }

}
