/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java */

package com.viaoa.javaparser;

public class ASTWhileStatement extends SimpleNode {
  public ASTWhileStatement(int id) {
    super(id);
  }

  public ASTWhileStatement(JavaParser p, int id) {
    super(p, id);
  }

}
